image:
  file: .gitpod.Dockerfile

tasks:
    - name: VNC Server
      command: vncserver -SecurityTypes None -depth 16 -geometry 1024x768

    - name: wait for port open and start Firefox
      command: |
          gp ports await 5901
          firefox-esr https://freebitco.in/?op=home# --display=:1 

    
