image:
  file: .gitpod.Dockerfile

tasks:
    - name: VNC Server
      command: vncserver -SecurityTypes None -depth 16 -geometry 1024x768

    - name: Start Firefox
      command: firefox https://freebitco.in/?op=home# --display=:1      



    
